# Generated by Django 2.2.8 on 2020-01-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geonames_place', '0004_change_meta_options_on_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='geonames_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
