# Generated by Django 2.2.6 on 2019-10-25 10:46

from django.conf import settings
from django.db import migrations


def load_data(apps, schema_editor):
    initial_data = settings.DEEDS_INITIAL_DATA

    for name in initial_data.keys():
        model = apps.get_model('deeds', name)
        for value in initial_data[name]:
            model.objects.get_or_create(title=value)


class Migration(migrations.Migration):

    dependencies = [
        ('deeds', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
