# Generated by Django 2.2.8 on 2019-12-25 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("deeds", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sources",
                to="deeds.Data",
            ),
        ),
    ]
